services:
  Coderun-postgresDB:
    image: postgres:17
    container_name: coderun_db
    environment:
      POSTGRES_DB: coderun
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres3101
    ports:
      - "5434:5432"